version: '3'

services:
  app1:
    build:
      context: ./app1
    ports:
      - "3001:8081"  # Map container port 8080 to host port 3001
    networks:
      - app-network

  app2:
    build:
      context: ./app2
    ports:
      - "3002:8082"  # Map container port 8081 to host port 3002
    networks:
      - app-network

  app3:
    build:
      context: ./app3
    ports:
      - "3003:8083"  # Map container port 8082 to host port 3003
    networks:
      - app-network

  loadbalancer:
    image: nginx:latest
    ports:
      - "80:80"  # Expose Nginx on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount nginx.conf into the container
    networks:
      - app-network

networks:
  app-network:
